Candidate: CVE-2025-32914
PublicDate: 2025-04-14 15:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2025-32914
 https://gitlab.gnome.org/GNOME/libsoup/-/issues/436
 https://access.redhat.com/security/cve/CVE-2025-32914
 https://bugzilla.redhat.com/show_bug.cgi?id=2359358
Description:
 A flaw was found in libsoup, where the soup_multipart_new_from_message()
 function is vulnerable to an out-of-bounds read. This flaw allows a
 malicious HTTP client to induce the libsoup server to read out of bounds.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to: hlibk
CVSS:
 nvd: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H [7.4 HIGH]

Patches_libsoup2.4:
upstream_libsoup2.4: needs-triage
esm-infra/xenial_libsoup2.4: needs-triage
esm-infra/bionic_libsoup2.4: needs-triage
focal_libsoup2.4: needs-triage
jammy_libsoup2.4: needs-triage
noble_libsoup2.4: needs-triage
oracular_libsoup2.4: needs-triage
plucky_libsoup2.4: needs-triage
devel_libsoup2.4: needs-triage

Patches_libsoup3:
upstream_libsoup3: needs-triage
focal_libsoup3: DNE
jammy_libsoup3: needs-triage
esm-apps/jammy_libsoup3: needs-triage
noble_libsoup3: needs-triage
oracular_libsoup3: needs-triage
plucky_libsoup3: needs-triage
devel_libsoup3: needs-triage
