Candidate: CVE-2025-50817
PublicDate: 2025-08-14 17:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2025-50817
 https://medium.com/@abcd_68700/cve-2025-50817-python-future-module-arbitrary-code-execution-via-unintended-import-of-test-py-f0818ea93cf4
 https://github.com/PythonCharmers/python-future
 https://pypi.org/project/future/
Description:
 A vulnerability in the Python-Future 1.0.0 module allows for arbitrary code
 execution via the unintended import of a file named test.py. When the
 module is loaded, it automatically imports test.py, if present in the same
 directory or in the sys.path. This behavior can be exploited by an attacker
 who has the ability to write files to the server, allowing the execution of
 arbitrary code.
Ubuntu-Description:
Notes:
 mdeslaur> versions earlier than 1.0.0 are also affected, flaw introduced
 mdeslaur> in the following commit:
 mdeslaur> https://github.com/PythonCharmers/python-future/commit/b9c7593e4e1478240522a71a6c85ecd24cc3d20a
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 cisa-adp: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N [5.4 MEDIUM]

Patches_python-future:
upstream_python-future: needs-triage
esm-apps/xenial_python-future: needs-triage
esm-infra/bionic_python-future: needs-triage
esm-infra/focal_python-future: needs-triage
jammy_python-future: needed
noble_python-future: needed
esm-apps/noble_python-future: needed
plucky_python-future: DNE
devel_python-future: DNE
