Candidate: CVE-2025-61774
PublicDate: 2025-10-06 23:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2025-61774
 https://github.com/pyvista/pyvista/security/advisories/GHSA-xr7f-qcjc-63rv
 https://github.com/pyvista/pyvista/commit/aabfb3db2b0d4980de9e94e66272240efba4ed95
 https://github.com/pyvista/pyvista/blob/c96e1ddbe707fb7d3eb574dc3336de1a946f14a1/.devcontainer/offscreen/oncreatecommand.sh#L4
 https://github.com/pyvista/pyvista/blob/c96e1ddbe707fb7d3eb574dc3336de1a946f14a1/docker/slim.Dockerfile#L13
Description:
 PyVista provides 3D plotting and mesh analysis through an interface for the
 Visualization Toolkit (VTK). Version 0.46.3 of the PyVista Project is
 vulnerable to remote code execution via dependency confusion. Two pieces of
 code use`--extra-index-url`. But when `--extra-index-url` is used, pip
 always checks for the PyPI index first, and then the external index. One
 package listed in the code is not published in PyPI. If an attacker
 publishes a package with higher version in PyPI, the malicious code from
 the attacker controlled package may be pulled, leading to remote code
 execution and a supply chain attack. As of time of publication, a patched
 version is unavailable.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 github: CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N [9.3 CRITICAL]

Patches_python-pyvista:
upstream_python-pyvista: needs-triage
jammy_python-pyvista: DNE
noble_python-pyvista: DNE
plucky_python-pyvista: needs-triage
questing_python-pyvista: needs-triage
devel_python-pyvista: needs-triage
