PublicDateAtUSN: 2024-02-01 15:15:00 UTC
Candidate: CVE-2024-1141
PublicDate: 2024-02-01 15:15:00 UTC
References:
 https://access.redhat.com/security/cve/CVE-2024-1141
 https://ubuntu.com/security/notices/USN-6630-1
 https://www.cve.org/CVERecord?id=CVE-2024-1141
Description:
 A vulnerability was found in python-glance-store. The issue occurs when the
 package logs the access_key for the glance-store when the DEBUG log level
 is enabled.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 https://bugzilla.redhat.com/show_bug.cgi?id=2258836
 https://bugs.launchpad.net/glance-store/+bug/2047688
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 redhat: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N [5.5 MEDIUM]
 nvd: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N [5.5 MEDIUM]


Patches_python-glance-store:
 upstream: https://github.com/openstack/glance_store/commit/a5ba027922ba1230b4ae9abb810f36427be6354a
 upstream: https://github.com/openstack/glance_store/commit/d6e531af4821c8466b1e9404f12f89f6216417f2
upstream_python-glance-store: needs-triage
trusty_python-glance-store: DNE
xenial_python-glance-store: ignored (end of standard support)
esm-infra/xenial_python-glance-store: needs-triage
bionic_python-glance-store: ignored (end of standard support)
esm-infra/bionic_python-glance-store: needs-triage
focal_python-glance-store: released (2.0.0-0ubuntu4.3)
esm-infra/focal_python-glance-store: released (2.0.0-0ubuntu4.3)
jammy_python-glance-store: released (3.0.0-0ubuntu1.4)
mantic_python-glance-store: released (4.6.1-0ubuntu1.1)
noble_python-glance-store: released (4.6.1-0ubuntu3)
oracular_python-glance-store: released (4.6.1-0ubuntu3)
plucky_python-glance-store: released (4.6.1-0ubuntu3)
questing_python-glance-store: released (4.6.1-0ubuntu3)
devel_python-glance-store: released (4.6.1-0ubuntu3)
