PublicDateAtUSN: 2011-10-19
Candidate: CVE-2011-4137
PublicDate: 2011-10-19 10:55:00 UTC
References:
 https://ubuntu.com/security/notices/USN-1297-1
 https://www.cve.org/CVERecord?id=CVE-2011-4137
Description:
 The verify_exists functionality in the URLField implementation in Django
 before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt
 access to an arbitrary URL with no timeout, which allows remote attackers
 to cause a denial of service (resource consumption) via a URL associated
 with (1) a slow response, (2) a completed TCP connection with no
 application data sent, or (3) a large amount of application data, a related
 issue to CVE-2011-1521.
Ubuntu-Description:
Notes:
Bugs:
Priority: medium
Discovered-by: Paul McMillan
Assigned-to:
CVSS: 

Patches_python-django:
 upstream: https://code.djangoproject.com/changeset/16766 (1.2)
 upstream: https://code.djangoproject.com/changeset/16763 (1.3)
upstream_python-django: released (1.3.1-1)
hardy_python-django: ignored (end of life)
lucid_python-django: released (1.1.1-2ubuntu1.4)
maverick_python-django: released (1.2.3-1ubuntu0.2.10.10.3)
natty_python-django: released (1.2.5-1ubuntu1.1)
oneiric_python-django: released (1.3-2ubuntu1.1)
devel_python-django: not-affected (1.3.1-1ubuntu1)
