Candidate: CVE-2022-30284
PublicDate: 2022-05-04 22:15:00 UTC
References:
 https://www.swascan.com/security-advisory-libnmap-2/
 https://github.com/savon-noir/python-libnmap/releases
 https://pypi.org/project/python-libnmap/
 https://www.cve.org/CVERecord?id=CVE-2022-30284
Description:
 ** DISPUTED ** In the python-libnmap package through 0.7.2 for Python,
 remote command execution can occur (if used in a client application that
 does not validate arguments). NOTE: the vendor believes it would be
 unrealistic for an application to call NmapProcess with arguments taken
 from input data that arrived over an untrusted network, and thus the CVSS
 score corresponds to an unrealistic use case. None of the NmapProcess
 documentation implies that this is an expected use case.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H [9.8 CRITICAL]
 mitre: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:H [9.0 CRITICAL]


Patches_python-libnmap:
upstream_python-libnmap: needs-triage
focal_python-libnmap: not-affected (disputed)
esm-infra/focal_python-libnmap: DNE (focal was not-affected [disputed])
esm-apps/focal_python-libnmap: not-affected (disputed)
impish_python-libnmap: ignored (end of life)
jammy_python-libnmap: not-affected (disputed)
esm-apps/jammy_python-libnmap: not-affected (disputed)
kinetic_python-libnmap: ignored (end of life, was needs-triage)
lunar_python-libnmap: ignored (end of life, was needs-triage)
mantic_python-libnmap: ignored (end of life, was needs-triage)
noble_python-libnmap: not-affected (disputed)
esm-apps/noble_python-libnmap: not-affected (disputed)
devel_python-libnmap: not-affected (disputed)
