Candidate: CVE-2020-15523
PublicDate: 2020-07-04 23:15:00 UTC
References:
 https://bugs.python.org/issue29778
 https://github.com/python/cpython/pull/21297
 https://www.cve.org/CVERecord?id=CVE-2020-15523
Description:
 In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and
 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in
 cases where CPython is embedded in a native application. This occurs
 because python3X.dll may use an invalid search path for python3.dll loading
 (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using
 python.exe from a standard (non-embedded) Python installation on Windows.
Ubuntu-Description:
Notes:
 mdeslaur> windows-specific issue, doesn't affect Ubuntu
Mitigation:
Bugs:
Priority: untriaged
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H [7.8 HIGH]


Patches_python3.8:
upstream_python3.8: not-affected (debian: Python on Windows)
precise/esm_python3.8: DNE
trusty_python3.8: ignored (end of standard support)
trusty/esm_python3.8: DNE
esm-infra-legacy/trusty_python3.8: DNE
xenial_python3.8: DNE
bionic_python3.8: not-affected
esm-apps/bionic_python3.8: not-affected
eoan_python3.8: not-affected
focal_python3.8: not-affected
esm-infra/focal_python3.8: not-affected
devel_python3.8: not-affected

Patches_python2.7:
upstream_python2.7: not-affected (debian: Python on Windows)
precise/esm_python2.7: not-affected
trusty_python2.7: ignored (end of standard support)
trusty/esm_python2.7: not-affected
esm-infra-legacy/trusty_python2.7: not-affected
xenial_python2.7: not-affected
esm-infra/xenial_python2.7: not-affected
bionic_python2.7: not-affected
esm-infra/bionic_python2.7: not-affected
eoan_python2.7: not-affected
focal_python2.7: not-affected
esm-apps/focal_python2.7: not-affected
devel_python2.7: not-affected
