Candidate: CVE-2013-6044
PublicDate: 2013-10-04 17:55:00 UTC
PublicDateAtUSN: 2013-09-24
References:
 https://www.djangoproject.com/weblog/2013/aug/13/security-releases-issued
 https://github.com/django/django/commit/ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a
 https://github.com/django/django/commit/ae3535169af804352517b7fea94a42a1c9c4b762
 https://github.com/django/django/commit/1a274ccd6bc1afbdac80344c9b6e5810c1162b5f
 http://xforce.iss.net/xforce/xfdb/86437
 http://www.securitytracker.com/id/1028915
 http://secunia.com/advisories/54476
 http://seclists.org/oss-sec/2013/q3/411
 http://seclists.org/oss-sec/2013/q3/369
 https://ubuntu.com/security/notices/USN-1967-1
 https://www.cve.org/CVERecord?id=CVE-2013-6044
Description:
 The is_safe_url function in utils/http.py in Django 1.4.x before 1.4.6,
 1.5.x before 1.5.2, and 1.6 before beta 2 treats a URL's scheme as safe
 even if it is not HTTP or HTTPS, which might introduce cross-site scripting
 (XSS) or other vulnerabilities into Django applications that use this
 function, as demonstrated by "the login view in django.contrib.auth.views"
 and the javascript: scheme.
Ubuntu-Description:
Notes:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS: 

Patches_python-django:
 upstream: https://github.com/django/django/commit/ec67af0bd609c412b76eaa4cc89968a2a8e5ad6a (1.4)
 upstream: https://github.com/django/django/commit/1a274ccd6bc1afbdac80344c9b6e5810c1162b5f (1.5)
upstream_python-django: released (1.4.6, 1.5.2)
lucid_python-django: released (1.1.1-2ubuntu1.9)
precise_python-django: released (1.3.1-4ubuntu1.8)
quantal_python-django: released (1.4.1-2ubuntu0.4)
raring_python-django: released (1.4.5-1ubuntu0.1)
devel_python-django: not-affected (1.5.4-1ubuntu1)
