PublicDateAtUSN: 2020-09-01 10:00:00 UTC
Candidate: CVE-2020-24583
CRD: 2020-09-01 10:00:00 UTC
PublicDate: 2020-09-01 13:15:00 UTC
References: 
 https://ubuntu.com/security/notices/USN-4479-1
 https://www.cve.org/CVERecord?id=CVE-2020-24583
Description:
 An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and
 3.1 before 3.1.1 (when Python 3.7+ is used).
 FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to
 intermediate-level directories created in the process of uploading files.
 It was also not applied to intermediate-level collected static directories
 when using the collectstatic management command.
Ubuntu-Description: 
Notes: 
 mdeslaur> This issue is caused by a behavioural change in Python 3.7.
 mdeslaur> While python3.7 is available for bionic, it doesn't replace
 mdeslaur> python3.6, so bionic is not affected by this issue.
Mitigation: 
Bugs: 
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N [7.5 HIGH]


Patches_python-django:
upstream_python-django: released (2.2.16)
precise/esm_python-django: DNE
trusty_python-django: ignored (end of standard support)
trusty/esm_python-django: not-affected (doesn't use python3.7)
esm-infra-legacy/trusty_python-django: not-affected (doesn't use python3.7)
xenial_python-django: not-affected (doesn't use python3.7)
esm-infra/xenial_python-django: not-affected (doesn't use python3.7)
bionic_python-django: not-affected (doesn't use python3.7)
esm-infra/bionic_python-django: not-affected (doesn't use python3.7)
focal_python-django: released (2:2.2.12-1ubuntu0.2)
esm-infra/focal_python-django: released (2:2.2.12-1ubuntu0.2)
devel_python-django: released (2:2.2.16-1)
