PublicDateAtUSN: 2019-04-18
Candidate: CVE-2019-11324
PublicDate: 2019-04-18 21:29:00 UTC
References:
 https://www.openwall.com/lists/oss-security/2019/04/17/3
 http://www.openwall.com/lists/oss-security/2019/04/19/1
 https://ubuntu.com/security/notices/USN-3990-1
 https://www.cve.org/CVERecord?id=CVE-2019-11324
Description:
 The urllib3 library before 1.24.2 for Python mishandles certain cases where
 the desired set of CA certificates is different from the OS store of CA
 certificates, which results in SSL connections succeeding in situations
 where a verification failure is the correct outcome. This is related to use
 of the ssl_context, ca_certs, or ca_certs_dir argument.
Ubuntu-Description:
Notes:
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927412
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N [7.5 HIGH]


Patches_python-urllib3:
 upstream: https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4
upstream_python-urllib3: released (1.24.2)
precise/esm_python-urllib3: DNE
trusty_python-urllib3: ignored (end of standard support)
trusty/esm_python-urllib3: not-affected (code not present)
esm-infra-legacy/trusty_python-urllib3: not-affected (code not present)
xenial_python-urllib3: not-affected (code not present)
esm-infra/xenial_python-urllib3: not-affected (code not present)
bionic_python-urllib3: released (1.22-1ubuntu0.18.04.1)
esm-infra/bionic_python-urllib3: not-affected (1.22-1ubuntu0.18.04.1)
cosmic_python-urllib3: released (1.22-1ubuntu0.18.10.1)
disco_python-urllib3: released (1.24.1-1ubuntu0.1)
devel_python-urllib3: released (1.24.1-1ubuntu1)
